### ISSUE TITLE
能增加多账号吗？

### ISSUE THREAD

**Issue by tobycroft** [Tarocch1/mirai-http-center#1]
能增加多账号吗？看着现在这个只支持一个，我看console是可以登录多个的，可以实现吗

**Comment by Tarocch1** [comment]
之前考虑过，我觉得运行多个实例是一种更好的解决办法。

**Comment by tobycroft** [comment]
如果可以做到单例的话是最好的，多实例维护起来难度比较大，虽然可以用docker，不过因为配置文件不能通用，所以要独立准备配置文件，如果可以在docker加载的时候填写qq这些信息，那相对的话切换会更方便

**Comment by Tarocch1** [comment]
多账号一般来说会有不同的schema需求，所以配置上单例多账号也不会使得配置总量减少多少，相反会提升单个配置文件复杂度，这不是单纯docker加载时填写qq就能解决的问题。这个功能近期应该不会实现，如果你有好的解决方案欢迎pr。
